import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {displacement, flexuralOmega, flexuralPhaseVelocity, flexuralGroupVelocity, nondispersiveOmega, TAU} from './physics.js';

const waves={
 p:{name:'Longitudinal P wave',geometry:'block',motion:'Particle motion is parallel to propagation. Alternating compression and tension travel through the block.'},
 sh:{name:'Shear-horizontal SH wave',geometry:'block',motion:'Particle motion is horizontal and perpendicular to propagation. The displayed field is signed shear.'},
 sv:{name:'Shear-vertical SV wave',geometry:'block',motion:'Particle motion is vertical and perpendicular to propagation. The displayed field is signed shear.'},
 rayleigh:{name:'Rayleigh surface wave',geometry:'block',motion:'Particles trace retrograde ellipses in a vertical plane. Motion decays approximately exponentially with depth.'},
 a0:{name:'Flexural A0-like plate wave',geometry:'plate',motion:'Dominant motion is out of plane, with opposite in-plane motion above and below the mid-plane. This is a low-frequency thin-plate approximation.'},
 s0:{name:'Extensional S0-like plate wave',geometry:'plate',motion:'Dominant motion is in-plane and parallel to propagation; thickness contraction/expansion is shown weakly.'}
};
const blockWaves=['p','sh','sv','rayleigh'], plateWaves=['a0','s0'];
const $=id=>document.getElementById(id);
const state={playing:true,time:0,geometry:'block',wave:'p',density:'medium',frequency:1,wavelength:4,amplitude:1.3,slice:.5,impact:null};
let viewA,viewB,last=performance.now();

class WaveView{
 constructor(el,comparison=false){this.el=el;this.comparison=comparison;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0xdfe7ec);this.camera=new THREE.PerspectiveCamera(38,1,.1,100);this.camera.position.set(8,6,8);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));el.appendChild(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.minDistance=4;this.controls.maxDistance=24;this.root=new THREE.Group();this.scene.add(this.root);this.scene.add(new THREE.HemisphereLight(0xffffff,0x48606b,2.2));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(4,8,6);this.scene.add(dl);this.resize();new ResizeObserver(()=>this.resize()).observe(el);this.renderer.domElement.addEventListener('pointerdown',e=>this.tap(e));}
 resize(){const w=this.el.clientWidth,h=this.el.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 clear(){while(this.root.children.length){const o=this.root.children.pop();o.geometry?.dispose();o.material?.dispose()}}
 build(){this.clear();this.points=[];this.refs=[];this.arrows=[];this.trailLines=[];const d=state.density==='low'?[13,6,5]:state.density==='high'?[25,12,9]:[19,9,7];let [nx,ny,nz]=d;if(state.geometry==='plate')nz=state.density==='high'?5:3;const L=8,W=4,H=state.geometry==='plate'?.7:3.2;const geo=new THREE.SphereGeometry(state.density==='high'?.055:.075,7,6);const mat=new THREE.MeshStandardMaterial({color:0x1976a3,roughness:.55});const refMat=new THREE.MeshBasicMaterial({color:0x70838f,transparent:true,opacity:.18});for(let i=0;i<nx;i++)for(let j=0;j<ny;j++)for(let k=0;k<nz;k++){const p=new THREE.Vector3(-L/2+L*i/(nx-1),-W/2+W*j/(ny-1),-H/2+H*k/(nz-1));const m=new THREE.Mesh(geo,mat.clone());m.userData.p=p;m.position.copy(p);this.root.add(m);this.points.push(m);const r=new THREE.Mesh(geo,refMat);r.position.copy(p);this.root.add(r);this.refs.push(r)}this.addGuide(L,W,H);this.makeArrows();this.makeTrails();this.setCamera($('camera').value);}
 addGuide(L,W,H){const box=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(L,W,H)),new THREE.LineBasicMaterial({color:0x40515b,transparent:true,opacity:.45}));this.root.add(box);this.propagation=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(-L/2-1,0,H/2+.8),L+1,0x111111,.45,.25);this.root.add(this.propagation);const pg=new THREE.PlaneGeometry(W,H+1),pm=new THREE.MeshBasicMaterial({color:0xffc107,transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false});this.sliceMesh=new THREE.Mesh(pg,pm);this.sliceMesh.rotation.y=Math.PI/2;this.root.add(this.sliceMesh)}
 makeArrows(){const selected=this.points.filter((_,i)=>i%Math.max(1,Math.floor(this.points.length/24))===0);for(const p of selected){const a=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),p.position,.25,0x7c3aed,.16,.09);a.userData.source=p;this.root.add(a);this.arrows.push(a)}}
 makeTrails(){const selected=this.points.filter((_,i)=>i%Math.max(1,Math.floor(this.points.length/12))===0);for(const p of selected){const g=new THREE.BufferGeometry();const arr=new Float32Array(33*3);g.setAttribute('position',new THREE.BufferAttribute(arr,3));const l=new THREE.Line(g,new THREE.LineBasicMaterial({color:0x6d28d9,transparent:true,opacity:.65}));l.userData.source=p;this.root.add(l);this.trailLines.push(l)}}
 update(t){const cfg={amplitude:.28*state.amplitude,wavelength:state.wavelength,frequency:state.frequency};const colA=new THREE.Color(0x0072b2),colB=new THREE.Color(0xf4f4f4),colC=new THREE.Color(0xd55e00),shA=new THREE.Color(0x009e73),shC=new THREE.Color(0xcc79a7);let max=.001;for(const m of this.points){const p=m.userData.p;const u=displacement(state.wave,p,t,cfg);max=Math.max(max,Math.abs(u.scalar));m.position.set(p.x+u.x,p.y+u.y,p.z+u.z);if(this.comparison)m.position.set(p.x,p.y,p.z).add(new THREE.Vector3(u.x,u.y,u.z).multiplyScalar(1.4));m.visible=!$('crossSection').checked||Math.abs((p.x+4)/8-state.slice)<.12;if($('colors').checked){const q=Math.max(-1,Math.min(1,u.scalar/(cfg.amplitude*TAU/state.wavelength)));const a=u.field==='shear'?shA:colA,c=u.field==='shear'?shC:colC;m.material.color.copy(q<0?a:colB).lerp(q<0?colB:c,Math.abs(q))}else m.material.color.set(0x1976a3)}this.refs.forEach(r=>r.visible=$('reference').checked);this.sliceMesh.visible=$('crossSection').checked;this.sliceMesh.position.x=-4+8*state.slice;this.arrows.forEach(a=>{const m=a.userData.source,p=m.userData.p,u=displacement(state.wave,p,t,cfg),v=new THREE.Vector3(u.x,u.y,u.z),len=v.length();a.position.copy(m.position);if(len>.0001)a.setDirection(v.normalize());a.setLength(.15+len*1.8,.13,.08);a.visible=$('vectors').checked&&m.visible});this.trailLines.forEach(l=>{const m=l.userData.source,p=m.userData.p,arr=l.geometry.attributes.position.array;for(let i=0;i<33;i++){const tt=t-i/(32*state.frequency),u=displacement(state.wave,p,tt,cfg);arr[3*i]=p.x+u.x;arr[3*i+1]=p.y+u.y;arr[3*i+2]=p.z+u.z}l.geometry.attributes.position.needsUpdate=true;l.visible=$('trails').checked&&m.visible});this.controls.update();this.renderer.render(this.scene,this.camera)}
 setCamera(v){const pos={perspective:[8,6,8],top:[0,11,.01],side:[0,-11,0],front:[11,0,0]}[v];this.camera.position.set(...pos);this.camera.up.set(0,0,1);if(v==='top')this.camera.up.set(0,1,0);this.controls.target.set(0,0,0);this.controls.update()}
 tap(){if(!state.impact)return;showCoupling(state.impact)}
}

function populateWaves(){const list=state.geometry==='block'?blockWaves:plateWaves;$('wave').innerHTML=list.map(k=>`<option value="${k}">${waves[k].name}</option>`).join('');if(!list.includes(state.wave))state.wave=list[0];$('wave').value=state.wave}
function rebuild(){populateWaves();viewA?.build();viewB?.build();updateText()}
function updateText(){const w=waves[state.wave];$('modeTitle').textContent=w.name;$('motionText').textContent=w.motion;$('frequencyOut').textContent=state.frequency.toFixed(2)+' Hz';$('wavelengthOut').textContent=state.wavelength.toFixed(1)+' m';$('amplitudeOut').textContent=state.amplitude.toFixed(1)+'×';$('sliceOut').textContent=Math.round(state.slice*100)+'%';const shear=['sh','sv'].includes(state.wave);$('legend').innerHTML=`<b>${shear?'Signed shear strain proxy':'Compression / tension proxy'}</b><span class="legend-row"><i class="swatch ${shear?'shear':''}"></i>${shear?'negative shear — zero — positive shear':'compression — neutral — tension'}</span><small>Arrows and trajectories remain visible, so color is not the sole encoding.</small>`}
function showCoupling(kind){const block={normal:{p:.15,sh:.05,sv:.65,rayleigh:.85},longitudinal:{p:.9,sh:.05,sv:.12,rayleigh:.35},transverse:{p:.05,sh:.9,sv:.18,rayleigh:.2}},plate={normal:{a0:.95,s0:.15},longitudinal:{a0:.25,s0:.9},transverse:{a0:.2,s0:.15}};const vals=(state.geometry==='block'?block:plate)[kind];$('coupling').innerHTML=Object.entries(vals).map(([k,v])=>`<div class="bar"><span>${waves[k].name.replace(/ wave| plate wave/g,'')}</span><i style="width:${v*100}%"></i><b>${Math.round(v*100)}%</b></div>`).join('')+'<small>Approximate relative excitation strength based on force direction and modal symmetry.</small>'}

function drawDispersion(){const c=$('dispersionCanvas'),x=c.getContext('2d'),W=c.width,H=c.height;x.clearRect(0,0,W,H);x.strokeStyle='#cad5dc';x.beginPath();x.moveTo(30,H/2);x.lineTo(W-20,H/2);x.stroke();const real=$('realDispersion').checked,t=state.time*5,ks=[1.4,2.0,2.8,3.7],amps=[1,.8,.55,.32];x.lineWidth=3;x.strokeStyle='#075985';x.beginPath();for(let px=0;px<W-50;px++){const xx=(px/(W-50))*16-4;let y=0;for(let i=0;i<ks.length;i++){const k=ks[i],om=real?flexuralOmega(k,.12,1,.35):nondispersiveOmega(k,1.25);y+=amps[i]*Math.cos(k*xx-om*t)*Math.exp(-Math.pow(xx-1.5,2)/5)}const py=H/2-y*25;x[px?'lineTo':'moveTo'](30+px,py)}x.stroke();const k0=2.3,vp=real?flexuralPhaseVelocity(k0,.12,1,.35):1.25,vg=real?flexuralGroupVelocity(k0,.12,1,.35):1.25;$('velocityText').textContent=`Representative k = ${k0.toFixed(1)} rad/m: phase velocity ≈ ${vp.toFixed(2)} m/s; group velocity ≈ ${vg.toFixed(2)} m/s. ${real?'Because vg = 2vp in this ideal thin-plate model, the envelope and crests do not travel together.':'Artificial nondispersive case: all components share the same speed.'}`}

const physicsHTML=`<p>Coordinates: x is propagation, y is horizontal transverse, z is vertical or through-thickness. Harmonic phase is q=kx−ωt, k=2π/λ and ω=2πf.</p><div class="equation">P: u=(A cos q,0,0)\nSH: u=(0,A cos q,0)\nSV: u=(0,0,A cos q)\nRayleigh: uₓ≈−0.72 A e^(−0.85k depth) sin q; u_z≈A e^(−0.85k depth) cos q\nA0-like: w=A cos q; uₓ≈0.45 A k z sin q\nS0-like: uₓ=A cos q; u_z≈−0.22 A k z sin q\nThin plate: ρh ẅ + D∇⁴w=0; D=Eh³/[12(1−ν²)]\nω=√(D/ρh) k²; cₚ=ω/k; c_g=dω/dk=2cₚ</div><p><b>Symbols:</b> A displacement amplitude; f frequency; λ wavelength; k wavenumber; ω angular frequency; t time; E Young’s modulus; ν Poisson ratio; ρ density; h plate thickness; D flexural rigidity; w transverse plate displacement.</p><p><b>Limitations:</b> linear, small-strain, isotropic homogeneous material; no boundaries, reflections, damping, mode conversion, anisotropy, finite-element stress recovery, exact Lamb dispersion curves, or exact Rayleigh eigenfunctions. Visual amplitude is exaggerated. Color fields are strain-like proxies for teaching, not calibrated stresses.</p>`;$('physics').innerHTML=physicsHTML;

function bind(){for(const id of ['frequency','wavelength','amplitude','slice'])$(id).addEventListener('input',e=>{state[id]=+e.target.value;updateText()});$('geometry').onchange=e=>{state.geometry=e.target.value;rebuild()};$('wave').onchange=e=>{state.wave=e.target.value;updateText()};$('density').onchange=e=>{state.density=e.target.value;rebuild()};$('camera').onchange=e=>{viewA.setCamera(e.target.value);viewB.setCamera(e.target.value)};$('playBtn').onclick=()=>{state.playing=!state.playing;$('playBtn').textContent=state.playing?'Pause':'Play'};$('backBtn').onclick=()=>{state.playing=false;state.time=Math.max(0,state.time-1/60);$('time').value=state.time%1};$('forwardBtn').onclick=()=>{state.playing=false;state.time+=1/60;$('time').value=state.time%1};$('time').oninput=e=>{state.playing=false;state.time=+e.target.value};$('resetBtn').onclick=()=>{Object.assign(state,{playing:true,time:0,geometry:'block',wave:'p',density:'medium',frequency:1,wavelength:4,amplitude:1.3,slice:.5});location.reload()};$('compare').onchange=e=>{$('viewB').classList.toggle('hidden',!e.target.checked);$('viewWrap').classList.toggle('compare',e.target.checked)};document.querySelectorAll('[data-impact]').forEach(b=>b.onclick=()=>{state.impact=b.dataset.impact;document.querySelectorAll('[data-impact]').forEach(x=>x.classList.toggle('primary',x===b));showCoupling(state.impact)});$('realDispersion').onchange=drawDispersion;$('pulse').onchange=e=>{if(e.target.checked){state.geometry='plate';state.wave='a0';$('geometry').value='plate';rebuild()}};tutorialBind()}
const tutorialSteps=[['1. Propagation direction','Find the large black +x arrow. It shows where the wave pattern travels; it does not show the direction followed by every particle.'],['2. Particle motion','Pause and step frame by frame. Purple arrows and trails show the displacement of selected material particles.'],['3. P versus shear','Compare P with SH and SV. P displacement is parallel to +x; shear displacement is perpendicular.'],['4. Rayleigh motion','Select Rayleigh. Surface particles trace ellipses and the motion decreases with depth.'],['5. A0 versus S0','Switch to the plate. A0 bends out of plane; S0 stretches mainly in plane.'],['6. Force coupling','Choose an impact direction, then tap the model. Compare qualitative excitation bars.'],['7. Flexural dispersion','Launch the flexural pulse and switch between artificial nondispersive and real thin-plate dispersion.']];let ti=0;function tutorialBind(){$('tutorialBtn').onclick=()=>{ti=0;showTutorial()};$('tutorialClose').onclick=()=> $('tutorial').classList.add('hidden');$('tutorialPrev').onclick=()=>{ti=Math.max(0,ti-1);showTutorial()};$('tutorialNext').onclick=()=>{if(ti<tutorialSteps.length-1){ti++;showTutorial()}else $('tutorial').classList.add('hidden')}}function showTutorial(){$('tutorial').classList.remove('hidden');$('tutorialTitle').textContent=tutorialSteps[ti][0];$('tutorialText').textContent=tutorialSteps[ti][1];$('tutorialNext').textContent=ti===tutorialSteps.length-1?'Finish':'Next'}

viewA=new WaveView($('viewA'));viewB=new WaveView($('viewB'),true);bind();rebuild();showCoupling('longitudinal');function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state.playing)state.time+=dt*($('slow').checked?.2:1);$('time').value=state.time%1;viewA.update(state.time);if(!$('viewB').classList.contains('hidden'))viewB.update(state.time);drawDispersion();requestAnimationFrame(loop)}requestAnimationFrame(loop);
